language: php
php:
    - 7.3
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
install:
    - travis_retry composer install --no-interaction
script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml
    - ./vendor/bin/psalm
after_success:
    - bash <(curl -s https://codecov.io/bash)
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
